{{
    config(
        materialized='table',
        database='TVC_SURVEYS_PROD',
        schema='PROD'
    )
}}

select
  src:survey_id::VARCHAR as survey_id,
  src:path::VARCHAR as path,
  src:title::VARCHAR as title, 
  src:lastSurveyEdit::VARCHAR as lastSurveyEdit,                             
  src :sampleSources::VARCHAR as sampleSources,                             
  src:groups::VARCHAR as groups,                                    
  src:closedDate::VARCHAR as closedDate,                                 
  src:questions::BIGINT as questions,                                  
  src:owner::BIGINT as owner,                                   
  src:total::BIGINT as total,                                      
  src:finishTime::VARCHAR as finishTime,                                
  src:compat::BIGINT as compat,                                     
  src:archived::BOOLEAN as archived,                                   
  src:clickthrough::BIGINT as clickthrough,                              
  src:medianQtime::VARCHAR as medianQtime,                               
  src:state::VARCHAR as state,                                      
  src:dateLaunched::VARCHAR as dateLaunched,                               
  src:type::BIGINT as type,                                       
  src:today::VARCHAR as today,                                     
  src:category::VARCHAR as category,                                   
  src:description::VARCHAR as description,                               
  src:tags::VARCHAR as tags,                                    
  src:usesLogic::BOOLEAN as usesLogic,                                 
  src:myAccess::VARCHAR as myAccess,                               
  src:averageQtime::VARCHAR as averageQtime,                              
  src:otherLanguages::VARCHAR as otherLanguages,                          
  src:qualified::BIGINT as qualified,                             
  src:myEdit::VARCHAR as myEdit,                                    
  src:startTime::VARCHAR as startTime,                               
  src:active::BOOLEAN as active,                                
  src:hasProjectParameters::BOOLEAN as hasProjectParameters,                     
  src:lang::VARCHAR as lang,                                    
  src:isCATI::BOOLEAN as isCATI,                                  
  src:lastEdit::VARCHAR as lastEdit,                                  
  src:hasDashboard::BOOLEAN as hasDashboard,                              
  src:lastAccess::VARCHAR as lastAccess,                             
  src:createdOn::VARCHAR as createdOn,                                                                    
  src:favorite::BOOLEAN as favorite,                                 
  src:hasSavedReport::BOOLEAN as hasSavedReport,                             
  src:lastQuotaEdit::VARCHAR as lastQuotaEdit,                             
  src:directory::VARCHAR as directory,                                  
  src:accessed::VARCHAR as accessed,                                   
  src:"createdBy.email"::VARCHAR as "createdBy.email",                         
  src:"createdBy.id"::BIGINT as "createdBy.id",                             
  src:"createdBy.name"::VARCHAR as "createdBy.name",                           
  src:"retention.archive_days"::BIGINT as "retention.archive_days",                    
  src:"retention.clear_data_days"::BIGINT as "retention.clear_data_days",                 
  src:"retention.server_delete_days"::BIGINT as "retention.server_delete_days",             
  src:"retention.server_archive_days"::VARCHAR as "retention.server_archive_days",              
  src:"retention.server_clear_data_days"::VARCHAR as "retention.server_clear_data_days",           
  src:"lastAccessBy.email"::VARCHAR as "lastAccessBy.email",                       
  src:"lastAccessBy.id"::BIGINT as "lastAccessBy.id",                           
  src:"lastAccessBy.name"::VARCHAR as "lastAccessBy.name",                          
  src:"lastEditBy.email"::VARCHAR as "lastEditBy.email",                         
  src:"lastEditBy.id"::BIGINT as "lastEditBy.id",                           
  src:"lastEditBy.name"::VARCHAR as "lastEditBy.name",
  TO_TIMESTAMP(src:current_ts::STRING) AS Current_TS  
  FROM {{ source('FORSTA_DEV', 'SURVEYS_RAW') }}